activation: torch.nn.LeakyReLU()
average: weighted
base_encoder: paraphrase-mpnet-base-v2
criterion: torch.nn.BCEWithLogitsLoss(reduction='none')
data_path: ../data/
dataset: mimic
device: cuda
end_model_batch_size: 32
end_model_epochs: 20
end_model_lr: 1e-4
end_model_patience: 3
end_model_weight_decay: 1e-4
h_sizes:
- 768
- 512
- 256
- 273
label_model: data_programming
label_model_lr: 0.01
label_model_n_epochs: 100
max_num: 50000
min_df: 0.001
model_path: ../models/mimic/
n_bootstrap: 100
n_classes: 273
n_jobs: 10
ngram_range: !!python/tuple
- 1
- 273
normalize_embeddings: false
preds_path: ../results/mimic/
q_update_interval: 100
results_path: ../results/mimic/
self_train_batch_size: 8
self_train_lr: 1e-6
self_train_patience: 5
self_train_thresh: 1-2e-3
self_train_weight_decay: 1e-4
show_progress_bar: true
target_00: anemia, unspecified, disease, deficiency, specified, anemias, thalassemia, blood, crisis, hemolytic, sicklecell, congenital, neutropenia, iron, secondary, chronic, hereditary, due, without, cell, factor, disorder, hemorrhagic, purpura, thrombocytopenia, white, syndrome, acquired, aplastic, induced
target_01: unspecified, disease, heart, chronic, acute, infarction, artery, embolism, kidney, thrombosis, stage, failure, cerebrovascular, venous, without, episode, care, cerebral, late, effects, myocardial, hypertensive, syndrome, atherosclerosis, aneurysm, wall, specified, veins, diseases, rheumatic
target_02: congenital, anomalies, unspecified, specified, anomaly, cleft, complete, deficiency, incomplete, longitudinal, without, limb, system, syndrome, partial, stenosis, lip, atresia, palate, ear, pulmonary, spina, bifida, hydrocephalus, region, deformities, upper, unilateral, bilateral, uterus
target_03: unspecified, obstruction, without, mention, hemorrhage, ulcer, chronic, acute, perforation, hernia, specified, gangrene, intestine, cholecystitis, gastric, teeth, site, recurrent, dental, gallbladder, jaw, calculus, duodenal, disorders, anomalies, peptic, gastrojejunal, bile, duct, disorder
target_04: unspecified, type, diabetes, uncontrolled, disorders, deficiency, manifestations, stated, metabolism, specified, mention, mellitus, secondary, ii, juvenile, without, goiter, disorder, vitamin, thyrotoxic, crisis, storm, syndrome, complication, toxic, gouty, hypothyroidism, thyroiditis, chronic, coma
target_05: abnormal, nonspecific, abdominal, unspecified, findings, smear, papanicolaou, pain, function, quadrant, squamous, symptoms, swelling, mass, lump, study, involving, examination, results, sleep, system, incontinence, pelvic, rigidity, tenderness, radiological, high, grade, intraepithelial, lesion
target_06: unspecified, specified, chronic, lesion, female, kidney, acute, glomerulonephritis, disorders, genital, urinary, prostate, cervix, classified, elsewhere, renal, disorder, urethral, breast, diseases, tract, disease, bladder, nephropathy, without, organs, vulva, prolapse, obstruction, inflammatory
target_07: tuberculosis, found, unspecified, bacilli, bacteriological, examination, tubercle, histological, specified, sputum, microscopy, confirmed, infection, tuberculous, due, bacterial, done, unknown, present, culture, histologically, methods, inoculation, animals, acute, gonococcal, fever, hepatitis, viral, primary
target_08: open, unspecified, fracture, injury, loss, without, wound, consciousness, closed, mention, intracranial, degree, skull, body, hemorrhage, level, third, burn, poisoning, hours, deep, contusion, part, involving, laceration, dislocation, prolonged, return, conscious, multiple
target_09: disorder, unspecified, type, episode, remission, dependence, schizophrenia, abuse, specified, drug, bipolar, disorders, acute, current, chronic, psychotic, episodic, manic, affective, recent, depressive, continuous, subchronic, exacerbation, personality, conduct, mental, dementia, severe, mixed
target_10: unspecified, region, arthropathy, joint, sites, specified, associated, site, foot, hand, ankle, shoulder, upper, forearm, pelvic, thigh, arm, lower, leg, multiple, acquired, diseases, arthritis, osteoarthrosis, osteomyelitis, elsewhere, classified, localized, bone, disorder
target_11: neoplasm, malignant, unspecified, lymph, nodes, benign, sites, cell, limb, site, lymphoma, hodgkins, skin, specified, carcinoma, leukemia, disease, tumor, remission, upper, lower, face, carcinoid, neck, situ, organ, uncertain, behavior, secondary, tissue
target_12: migraine, without, unspecified, intractable, mention, status, migrainosus, elsewhere, classified, epilepsy, sleep, diseases, cerebral, stated, disorder, headache, aura, nerve, meningitis, syndrome, due, disorders, affecting, side, chronic, limb, disease, specified, hemiplegia, acute
target_13: newborn, fetus, grams, fetal, affecting, unspecified, malnutrition, lightfordates, without, mention, due, neonatal, respiratory, hemorrhage, maternal, birth, placenta, perinatal, breast, milk, delivery, signs, preterm, infants, gestation, aspiration, via, specified, labor, growth
target_14: condition, complication, unspecified, antepartum, mention, delivered, without, care, episode, applicable, postpartum, pregnancy, mother, abortion, labor, complicating, childbirth, puerperium, delivery, complicated, complications, associated, induced, fetal, specified, hemorrhage, affecting, management, fetus, pelvic
target_15: due, acute, pneumonia, unspecified, chronic, respiratory, influenza, pulmonary, lung, virus, sinusitis, asthma, obstruction, bronchitis, diseases, elsewhere, classified, larynx, manifestations, without, disease, identified, pneumonitis, interstitial, allergic, specified, exacerbation, mention, vocal, nasal
target_16: unspecified, eye, vision, impairment, disorders, retinal, corneal, glaucoma, acute, associated, loss, ear, chronic, otitis, cataract, eyelid, disorder, body, visual, optic, hearing, media, specified, better, lesser, detachment, total, retinopathy, stage, degeneration
target_17: due, unspecified, dermatitis, ulcer, specified, abscess, pressure, cellulitis, skin, contact, erythematous, condition, body, carbuncle, furuncle, eczema, exfoliation, involving, percent, surface, urticaria, tissue, conditions, erythema, hair, except, foot, cyst, subcutaneous, seborrheic
target_18: accident, injuring, unspecified, vehicle, involving, history, motor, causing, effects, use, accidental, therapeutic, adverse, poisoning, personal, specified, injury, due, collision, screening, occupant, traffic, person, transport, fall, water, examination, malignant, caused, family
topk: 100
use_custom_encoder: false
use_noise_aware_loss: true
